import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "../components/global/NavBar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/global/ScrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.className} bg-muted/60`}>
          <NavBar />
          {children}
          <ScrollToTop />
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
